### ISSUE TITLE
Owncloud system tray not visible with Papirus Dark panel

### ISSUE THREAD

**Issue by BridouZ** [varlesh/papirus-suite#101]
Hi varlesh and thanks a lot for your amazing work,

I recently discovered a bug with the owncloud system tray and th Papirus dark panel. With that black panel the system tray icon, which is black, is not visible.

I don't know if you can fix that but I wanted to signal this bug to you.

**Comment by varlesh** [comment]
Thx )
icon **owncloud** available only for apps 48x48, 32x32.
Also for folders **folder-owncloud** 16x16, 32x32, 48x48 and 64x64
What icon name use on tray? Maybe icon binary?
PS: Sorry, i'm not use owncloud and don't know ))

**Comment by varlesh** [comment]
This icons use on tray?
![2016-02-29 21-55-30](https://cloud.githubusercontent.com/assets/8083855/13405400/3a8201c4-df2f-11e5-8d8f-3e439583d5b5.png)

**Comment by BridouZ** [comment]
I will try to find out and go back to you when I find the culprit ^^
