### ISSUE TITLE
[Plasma Theme] Need help :(

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-suite#102]
Buttons overlap. backgrounds and stroke transparent - that looks badly.
![screenshot_20160304_201134](https://cloud.githubusercontent.com/assets/8083855/13534349/c4d1b3ba-e245-11e5-8f26-ea238e520d1c.png)
![screenshot_20160304_201152](https://cloud.githubusercontent.com/assets/8083855/13534350/c4d24d02-e245-11e5-80a5-ee18f321e2e9.png)
How solwe this problem with transparent buttons?

**Comment by varlesh** [comment]
Use https://github.com/varlesh/papirus-suite/blob/master/kde-pack/plasma-themes/papirus-dark/widgets/busywidget.svgz

**Comment by FadeMind** [comment]
@varlesh  I will look later on plasma issue. Look here: https://github.com/FadeMind/papirus-wallpapers

**Comment by varlesh** [comment]
@FadeMind Very good :+1:

**Comment by varlesh** [comment]
@FadeMind But... it's not my wallpaper. I don't know who author this image (i'm only colorspace Gray and revert horizontal - for light theme negate).
Original:
![prime dark](https://cloud.githubusercontent.com/assets/8083855/13537367/a60e5bf8-e255-11e5-9a21-579be237cc77.png)

**Comment by varlesh** [comment]
mediainfo show only:
General
Complete name                            : Prime Dark.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 306 KiB

Image
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Width                                    : 2 400 pixels
Height                                   : 1 350 pixels
Bit depth                                : 32 bits
Compression mode                         : Lossless
Stream size                              : 306 KiB (100%)

**Comment by FadeMind** [comment]
@varlesh  it is [similar to Plasma 5 wallpaper set](https://www.google.pl/search?q=kde+plasma+wallpaper&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjtoPeS36fLAhXjFZoKHcO9A6kQ_AUIBygB&biw=1366&bih=667)

So. You customize it. so You are author of customization. 

And one more. Where you find this main wallpaper?

**Comment by varlesh** [comment]
i found on my PC :)

**Comment by FadeMind** [comment]
So it is made by you and it is fine. Google didn't find any identical looking wallpaper ;)

BTW. I improved README.md file: https://github.com/FadeMind/papirus-wallpapers

**Comment by FadeMind** [comment]
Move mouse cursor over screenshot for prompt ;)

**Comment by varlesh** [comment]
Maybe add wallpapers on papirus-suite?

**Comment by FadeMind** [comment]
@varlesh as how to Install instruction please.

**Comment by varlesh** [comment]
ok
