### ISSUE TITLE
Request: Add user color scheme support

### ISSUE THREAD

**Issue by AndydeCleyre** [varlesh/papirus-suite#105]
From https://www.kde.org/announcements/plasma-5.6.0.php :

> The default Plasma theme, Breeze, now follows the application color scheme allowing for a more personalized experience. A new 'Breeze Light' together with 'Breeze Dark' theme can be used to bring back the previous behavior. Additionally, tooltip animations have become more subtle.

Can we get a similar color behavior, but with these nice Papirus icons?

**Comment by varlesh** [comment]
Color schemes already available:
https://github.com/varlesh/papirus-suite/tree/master/kde-pack/color-schemes

**Comment by AndydeCleyre** [comment]
I don't mean to request that a user be able to choose a Papirus color scheme for their Qt/KDE interfaces, as that is already possible, as you note.

What I mean to request is that a user be able to choose and customize any Qt/KDE color scheme they want from the variety available and possible (which is already the case), and then have the **Papirus plasma theme incorporate that user's arbitrary color choices**, as the Breeze plasma theme now does.

**Comment by FadeMind** [comment]
@varlesh you miss understood.
See:
![s](https://www.kde.org/announcements/plasma-5.6/colour-schemes.png)
> Breeze Color Scheme Support
The default Plasma theme, Breeze, now follows the application color scheme allowing for a more personalized experience. A new 'Breeze Light' together with 'Breeze Dark' theme can be used to bring back the previous behavior. Aditionally, tooltip animations have become more subtle.

https://quickgit.kde.org/?p=breeze.git&a=commitdiff&h=9920983f869b3e3654c97ea4b623c0f4e8c8fae7

Changes in breeze CODE are a lot

https://quickgit.kde.org/?p=breeze.git&a=shortlog

**Comment by varlesh** [comment]
I see add new section colors:
```
[Colors:Complementary]
BackgroundAlternate=59,64,69
BackgroundNormal=49,54,59
DecorationFocus=30,146,255
DecorationHover=61,174,230
ForegroundActive=246,116,0
ForegroundInactive=175,176,179
ForegroundLink=61,174,230
ForegroundNegative=237,21,21
ForegroundNeutral=201,206,59
ForegroundNormal=239,240,241
ForegroundPositive=17,209,22
ForegroundVisited=61,174,230
```
You mean this?

**Comment by FadeMind** [comment]
@varlesh If this is NEW in colors, so this is IT ;)

**Comment by varlesh** [comment]
Ok, i check this later

**Comment by varlesh** [comment]
I check this with Air plasma theme. This not working!
It's likely working only with Breeze
![screen](https://cloud.githubusercontent.com/assets/8083855/14174153/30502986-f74b-11e5-9393-ddbd4754c6a0.png)

**Comment by AndydeCleyre** [comment]
According to user jensreuterberg on reddit,

> Well yeah any theme designer can use the same effect as the Breeze theme. So thats up to the theme designer.

**Comment by varlesh** [comment]
You really like this? I'm not like this option, because this spoil style.
And i don't know how this work... Why this effect not working with official Air Plasma Theme?

**Comment by FadeMind** [comment]
@varlesh just ask developer of this changes:

https://www.blogger.com/profile/09467841190488432608

**Comment by AndydeCleyre** [comment]
I do really like it, but if I'm really the only one interested it's ok with me if you choose against it. I've achieved a tolerable arrangement by using the Breeze plasma theme, and

```bash
cd /usr/share/plasma/desktoptheme/default
rm -r icons
ln -s ../papirus-dark/icons ./
```

**Comment by AndydeCleyre** [comment]
This approach is moving beyond just plasma in 5.7, to "regular" icons as well: http://notmart.org/blog/2016/05/icon-colors/
