### ISSUE TITLE
GTK 3.20 compatibility

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#106]
@varlesh breeze-gtk based theme is out-of-date and looks ugly against major changes in GTK 3.20.x release.

**Comment by varlesh** [comment]
I check this latter

**Comment by FadeMind** [comment]
@varlesh upstream https://bugs.kde.org/show_bug.cgi?id=361249

**Comment by porkslapchop** [comment]
https://github.com/dirruk1/gnome-breeze

We could make a simple recolor of this.

**Comment by varlesh** [comment]
New release have different colors and style on code with 3.18. I'm apply fix, but this not working anymore.
https://github.com/varlesh/papirus-suite/blob/master/kde-pack/gtk-themes/papirus/.fix/fix.sh
I don't know GTK and soon release 3.22 and fix again - this infinitely problem

**Comment by FadeMind** [comment]
I made binary fork for 3.20: https://github.com/FadeMind/breeze-gtk

**Comment by varlesh** [comment]
We rework fix again :( Maybe later...

**Comment by FadeMind** [comment]
@varlesh Looking here:
https://github.com/FadeMind/breeze-gtk/tree/master/src

You need prepare only VALID colors scheme for papirus and papirus dark variant and call bash script.
Review bash script and python script here.

` sass` is taken from https://aur.archlinux.org/packages/ruby-sass/

**Comment by varlesh** [comment]
Add new version for GTK 3.20. Please test it:
https://github.com/varlesh/papirus-suite/tree/master/kde-pack/gtk-themes/papirus-test

**Comment by FadeMind** [comment]
@Did You based on lastest breeze sources?

**Comment by varlesh** [comment]
Based on https://github.com/dirruk1/gnome-breeze/tree/master/Breeze-gtk

**Comment by FadeMind** [comment]
@varlesh fine.
I care about bin fork: https://github.com/FadeMind/breeze-gtk against several GTK versions compatibility in main repo.

**Comment by FadeMind** [comment]
@varlesh All is good.

**Comment by varlesh** [comment]
@FadeMind thx, i test latter and it's all good - delete previous version.

**Comment by FadeMind** [comment]
@varlesh I tested some GTK2 and GTK3 apps and all looks fine in **GRAY** :laughing: 

If in future I will find any regressions, I will inform you ASAP.

**Comment by varlesh** [comment]
Firefox again bugged :(
Very contrast stroke on searchbar and panel menu:
![screenshot_20160531_130245](https://cloud.githubusercontent.com/assets/8083855/15670889/63edc3a6-2730-11e6-9b70-49f469496677.png)

**Comment by varlesh** [comment]
it's GTK engine bug? Because with Adwaita bug persist
![screenshot_20160531_131045](https://cloud.githubusercontent.com/assets/8083855/15671018/1dd469be-2731-11e6-9e92-d0a17914cad0.png)

**Comment by FadeMind** [comment]
@varlesh this is GTK3 feature :1234: 
Breeze and Adwaita looking identical (with black borders)

**Comment by varlesh** [comment]
@FadeMind It's strange, because papirus (not papirus-test)  theme not show this contrast borders.

**Comment by FadeMind** [comment]
@varlesh  cause papirus are for GTK 3.18, papirus-next is for 3.20 and FIREFOX is GTK3 based now.

**Comment by varlesh** [comment]
Ok, i'm  delete papirus and rename papirus-test to papirus

**Comment by FadeMind** [comment]
:ok:
