### ISSUE TITLE
Add support for additional buttons in window title

### ISSUE THREAD

**Issue by ul** [varlesh/papirus-suite#107]
KDE supports placing extra useful buttons to the window titlebar, but when Papirus window decoration is chosen, only app icon, minimize, maximize and close are shown despite of more buttons added in settings on the next tab.

**Comment by varlesh** [comment]
Used this icon names?
    case MinimizeButton:
("minimize");
    case MaximizeButton:
("maximize");
    case RestoreButton:
("restore");
    case CloseButton:
("close");
    case AllDesktopsButton:
("alldesktops");
    case KeepAboveButton:
("keepabove");
    case KeepBelowButton:
("keepbelow");
    case ShadeButton:
("shade");
    case HelpButton:
("help");
    case MenuButton:
("menu");

**Comment by ul** [comment]
Honestly, I'm totally incompetent in KDE internals. Just a quick guess that you are providing windows decoration as QtCurve styles, but QtCurve doesn't support all buttons. I see mention of those extra buttons in breeze sources: https://quickgit.kde.org/?p=breeze.git&a=blob&h=73aee6de3d5e1474d7af41998414617dde45bb95&hb=2201f90bd4848cd2f35d96174f6fb5a4506479fd&f=kdecoration%2Fbreezebutton.cpp

**Comment by varlesh** [comment]
Ok, thx. Added later

**Comment by varlesh** [comment]
![screenshot_20160405_192610](https://cloud.githubusercontent.com/assets/8083855/14289629/52308696-fb64-11e5-84d1-da3b7b6c22ee.png)
Coming soon

**Comment by ul** [comment]
Wow, thank you!
