### ISSUE TITLE
[missing] k3b legacy task icons missing

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#108]
@varlesh please review and add proper symlinks. Thanks. OFC in papirus icon theme are used SVG instead of PNG files (so target is NAME only).
![zaznaczenie_002](https://cloud.githubusercontent.com/assets/9846948/14314400/387ce72e-fbf7-11e5-9721-f40607303917.png)

![screenshot_20160406_130457](https://cloud.githubusercontent.com/assets/9846948/14314553/2ee645b0-fbf8-11e5-8921-684aec6124fb.png)

![screenshot_20160406_130532](https://cloud.githubusercontent.com/assets/9846948/14314569/43bc3940-fbf8-11e5-88b4-c01ade3e3e9f.png)

Tree with icon names in standard k3b package (arch linux).

    $ pwd
    /usr/share/apps/k3b/icons/oxygen
    $ tree
    .
    ├── 128x128
    │   ├── actions
    │   │   ├── tools-rip-audio-cd.png
    │   │   ├── tools-rip-video-cd.png
    │   │   └── tools-rip-video-dvd.png
    │   ├── devices
    │   │   ├── media-optical-audio.png
    │   │   ├── media-optical-cd-video.png
    │   │   ├── media-optical-dvd-video.png
    │   │   ├── media-optical-mixed-cd.png
    │   │   └── media-optical-video.png
    │   └── mimetypes
    │       └── application-x-k3b.png
    ├── 16x16
    │   ├── actions
    │   │   ├── tools-rip-audio-cd.png
    │   │   ├── tools-rip-video-cd.png
    │   │   └── tools-rip-video-dvd.png
    │   └── devices
    │       ├── media-optical-audio.png
    │       ├── media-optical-cd-video.png
    │       ├── media-optical-data.png
    │       ├── media-optical-mixed-cd.png
    │       └── media-optical-video.png
    ├── 22x22
    │   ├── actions
    │   │   ├── tools-rip-audio-cd.png
    │   │   ├── tools-rip-video-cd.png
    │   │   └── tools-rip-video-dvd.png
    │   └── devices
    │       ├── media-optical-audio.png
    │       ├── media-optical-cd-video.png
    │       ├── media-optical-data.png
    │       ├── media-optical-mixed-cd.png
    │       └── media-optical-video.png
    ├── 32x32
    │   ├── actions
    │   │   ├── tools-rip-audio-cd.png
    │   │   ├── tools-rip-video-cd.png
    │   │   └── tools-rip-video-dvd.png
    │   ├── devices
    │   │   ├── media-optical-audio.png
    │   │   ├── media-optical-cd-video.png
    │   │   ├── media-optical-data.png
    │   │   ├── media-optical-dvd-video.png
    │   │   ├── media-optical-mixed-cd.png
    │   │   └── media-optical-video.png
    │   └── mimetypes
    │       └── application-x-k3b.png
    ├── 48x48
    │   ├── actions
    │   │   ├── tools-rip-audio-cd.png
    │   │   ├── tools-rip-video-cd.png
    │   │   └── tools-rip-video-dvd.png
    │   ├── devices
    │   │   ├── media-optical-audio.png
    │   │   ├── media-optical-cd-video.png
    │   │   ├── media-optical-data.png
    │   │   ├── media-optical-dvd-video.png
    │   │   ├── media-optical-mixed-cd.png
    │   │   └── media-optical-video.png
    │   └── mimetypes
    │       └── application-x-k3b.png
    ├── 64x64
    │   ├── actions
    │   │   ├── tools-rip-audio-cd.png
    │   │   ├── tools-rip-video-cd.png
    │   │   └── tools-rip-video-dvd.png
    │   ├── devices
    │   │   ├── media-optical-audio.png
    │   │   ├── media-optical-cd-video.png
    │   │   ├── media-optical-dvd-video.png
    │   │   ├── media-optical-mixed-cd.png
    │   │   └── media-optical-video.png
    │   └── mimetypes
    │       └── application-x-k3b.png
    └── scalable
        ├── actions
        │   ├── tools-rip-audio-cd.svgz
        │   ├── tools-rip-video-cd.svgz
        │   └── tools-rip-video-dvd.svgz
        ├── devices
        │   ├── media-optical-audio.svgz
        │   ├── media-optical-cd-video.svgz
        │   ├── media-optical-data.svgz
        │   ├── media-optical-dvd-video.svgz
        │   ├── media-optical-mixed-cd.svgz
        │   └── media-optical-video.svgz
        └── mimetypes
            └── application-x-k3b.svgz
    
    26 directories, 64 files

**Comment by varlesh** [comment]
Need only symlinks with PNG's on main theme or this for "extra-icons" folder?

**Comment by FadeMind** [comment]
Create proper names new icons/symlinks IN **papirus icon theme** directly in proper sub categories  and sizes.  This is global system wide icons (like it was for krusader). This is not for extras.

oxygen mainly using PNG files, but in papirus icon theme MAIN format is SVG OFC, so use SVG files.

**Comment by varlesh** [comment]
If this working need moved icons for krusader and amarok too.
My theme not available 128x128 and 64x64/
Icons apply fully if create only this files?
16x16/devices/media-optical-cd-video.png
16x16/devices/media-optical-video.png
16x16/devices/media-optical-audio.png
16x16/devices/media-optical-data.png
16x16/devices/media-optical-mixed-cd.png
16x16/actions/tools-rip-video-cd.png
16x16/actions/tools-rip-video-dvd.png
16x16/actions/tools-rip-audio-cd.png
48x48/devices/media-optical-cd-video.png
48x48/devices/media-optical-video.png
48x48/devices/media-optical-audio.png
48x48/devices/media-optical-data.png
48x48/devices/media-optical-mixed-cd.png
48x48/actions/tools-rip-video-cd.png
48x48/actions/tools-rip-video-dvd.png
48x48/actions/tools-rip-audio-cd.png

**Comment by FadeMind** [comment]
IDK really. BUT actions tool-rip icons are ignored by K3B legacy (KDE4). So testing is needed for find out how it working.

Amarok is another app with independent theming.

**Comment by varlesh** [comment]
K3B planned port to KF5? Maybe we wait this?
I create script:
```
#/bin/bash

#16/actions
cd 16x16/actions
rsvg-convert tools-media-optical-format.svg -f png -o tools-rip-video-cd.png
ln -s tools-rip-video-cd.png tools-rip-video-dvd.png
ln -s tools-rip-video-cd.png tools-rip-audio-cd.png

#16/devices
cd ../devices
rsvg-convert media-optical.svg -f png -o media-optical-data.png
ln -s media-optical-data.png media-optical-cd-video.png
ln -s media-optical-data.png media-optical-video.png
ln -s media-optical-data.png media-optical-mixed-cd.png
ln -s media-optical-data.png media-optical-audio.png

#48
cd ../../48x48/devices
rsvg-convert media-optical.svg -f png -o media-optical-data.png
ln -s media-optical-data.png tools-rip-video-cd.png
ln -s media-optical-data.png tools-rip-video-dvd.png
ln -s media-optical-data.png tools-rip-audio-cd.png
ln -s media-optical-data.png media-optical-cd-video.png
ln -s media-optical-data.png media-optical-video.png
ln -s media-optical-data.png media-optical-mixed-cd.png
ln -s media-optical-data.png media-optical-audio.png
```
But this not working! K3B not apply this icons

**Comment by FadeMind** [comment]
Curently k3b KF5 port is under development. 
k3b kf5 port honor papirus icon theme OUT OF BOX. 
https://aur.archlinux.org/packages/k3b-frameworks-git

**Comment by varlesh** [comment]
haha, no. Papirus - not official KDE icon theme. Only Breeze everywhere.

**Comment by varlesh** [comment]
This variant not working too:
```
#/bin/bash
# Fix icons for K3B
mkdir -p ~/.local/share/icons/oxygen/16x16/{actions,devices}
mkdir -p ~/.local/share/icons/oxygen/48x48/{actions,devices}

#16/actions
rsvg-convert /usr/share/icons/papirus/16x16/actions/tools-media-optical-format.svg -f png -o ~/.local/share/icons/oxygen/16x16/actions/tools-rip-video-cd.png
cd ~/.local/share/icons/oxygen/16x16/actions
ln -s tools-rip-video-cd.png tools-rip-video-dvd.png
ln -s tools-rip-video-cd.png tools-rip-audio-cd.png

#16/devices
rsvg-convert /usr/share/icons/papirus/16x16/devices/media-optical.svg -f png -o ~/.local/share/icons/oxygen/16x16/devices/media-optical-data.png
cd ../devices
ln -s media-optical-data.png media-optical-cd-video.png
ln -s media-optical-data.png media-optical-video.png
ln -s media-optical-data.png media-optical-mixed-cd.png
ln -s media-optical-data.png media-optical-audio.png

#48
cd ../../48x48/actions
rsvg-convert /usr/share/icons/papirus/48x48/devices/media-optical.svg -f png -o ~/.local/share/icons/oxygen/48x48/actions/media-optical-data.png
ln -s media-optical-data.png tools-rip-video-cd.png
ln -s media-optical-data.png tools-rip-video-dvd.png
ln -s media-optical-data.png tools-rip-audio-cd.png
cd ../devices
rsvg-convert /usr/share/icons/papirus/48x48/devices/media-optical.svg -f png -o ~/.local/share/icons/oxygen/48x48/devices/media-optical-data.png
ln -s media-optical-data.png media-optical-cd-video.png
ln -s media-optical-data.png media-optical-video.png
ln -s media-optical-data.png media-optical-mixed-cd.png
ln -s media-optical-data.png media-optical-audio.png
cd
```

**Comment by FadeMind** [comment]
@varlesh k3b KF5 branch is under development but working like a charm (after applying FFMPEG patch)
 https://github.com/FadeMind/archpkgbuilds/tree/master/AUR/git-edge/k3b-frameworks-git

![zaznaczenie_001](https://cloud.githubusercontent.com/assets/9846948/15671340/ac46f0e2-272a-11e6-9367-909f1088b591.png)
