### ISSUE TITLE
Need fix scrollbars and menu select on GTK 3.20

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-suite#111]
@FadeMind I update gtk themes. Need fix scrollbars and menu select on GTK 3

**Comment by FadeMind** [comment]
@varlesh FYI: https://github.com/dirruk1/gnome-breeze/issues/56#issuecomment-210982910

**Comment by varlesh** [comment]
ok. If you or anybody find how fix this - can create PR for papirus.

**Comment by FadeMind** [comment]
@varlesh https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=911a48ea44ddca6c6448ec007debe5f89ee29e24

**Comment by FadeMind** [comment]
@varlesh great fix for scrollbars ;)

I have only one issue: white unseen titlebar looking:
![screenshot_20160426_114512](https://cloud.githubusercontent.com/assets/9846948/14813990/82bc64d8-0ba4-11e6-9b24-902be761ca53.png)

GNOME Disks

**Comment by FadeMind** [comment]
@varlesh :+1:  good job

**Comment by varlesh** [comment]
@FadeMind I update scrollbars for firefox gtk 3. 36419f1c24f9ec80beb642e327751047e5870371
 This working for you? Other GTK 3 apps show normal scrollbar too?

**Comment by varlesh** [comment]
@FadeMind And also please add depends [bomi-fresh](https://aur.archlinux.org/packages/bomi-fresh/) for bomi-skin-papirus-git

**Comment by FadeMind** [comment]
@varlesh 

![screenshot_20160427_165818](https://cloud.githubusercontent.com/assets/9846948/14856646/460cff02-0c99-11e6-9644-eb9c7501a42e.png)

FYI 
https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=e384f3d0297776eb00ddc1fbaecb8ae11194ca5a

Corebird (twitter client) have hidden scrollbar in default. After focus cursor right side of window scrollbar show and is operated.

![screenshot_20160427_170148](https://cloud.githubusercontent.com/assets/9846948/14856797/d183d452-0c99-11e6-9f0c-ef07c0fa2ec9.png)
![screenshot_20160427_170213](https://cloud.githubusercontent.com/assets/9846948/14856796/d1836562-0c99-11e6-87dd-39f3ba751757.png)

![screenshot_20160427_170405](https://cloud.githubusercontent.com/assets/9846948/14856865/2180e54e-0c9a-11e6-850e-d804a615ce81.png)
![screenshot_20160427_170427](https://cloud.githubusercontent.com/assets/9846948/14856866/21831d96-0c9a-11e6-9672-0d682a429238.png)

**Comment by varlesh** [comment]
@FadeMind Big thx, all working ) But i see transparent pixel line on scrollbar Bluefish - it's bug?

**Comment by FadeMind** [comment]
@varlesh  IMO yes.

**Comment by varlesh** [comment]
ok

**Comment by FadeMind** [comment]
@varlesh FIXED GNOME 3.20 breeze theme and improved 2.0 theme.
![screenshot_20160503_125752](https://cloud.githubusercontent.com/assets/9846948/14981326/a9d8acd6-112e-11e6-93c3-e265d1ce5e58.png)
[breeze-3.20-fixed.tar.gz](https://github.com/varlesh/papirus-suite/files/246722/breeze-3.20-fixed.tar.gz)
Scrollbars are fixed too:

![screenshot_20160503_130229](https://cloud.githubusercontent.com/assets/9846948/14981419/5466ea50-112f-11e6-95d8-dd3d5509a729.png)
Highlighted and bigger after mouse select:
![screenshot_20160503_130317](https://cloud.githubusercontent.com/assets/9846948/14981445/81fd4e64-112f-11e6-9bfb-fbe8a49c7a45.png)

Firefox
![screenshot_20160503_130615](https://cloud.githubusercontent.com/assets/9846948/14981482/d8dfa83a-112f-11e6-8bbc-2bbc2dbad0b7.png)

Reference

`git clone -b color-effects https://git@github.com/dirruk1/gnome-breeze.git`
