### ISSUE TITLE
Request: Use Kvantum instead of QTcurve

### ISSUE THREAD

**Issue by porkslapchop** [varlesh/papirus-suite#117]
https://github.com/tsujan/Kvantum

This Themeengine is pretty good and uses svg. Qtcurve is simply too old/deprecated.

**Comment by varlesh** [comment]
QtCurve have transparent option and hide menubar (with non-KDE Qt apps), because i add this style. I know QtCurve very old style.
But Kvantum have Enlightenment style, i don't know how this looking...
Maybe you show screens for example?

**Comment by porkslapchop** [comment]
![preview](https://cloud.githubusercontent.com/assets/19503886/15673449/fb41db92-2736-11e6-9084-e853b57b6d66.png)
Found this screen. Looks like you can do some neat stuff with it.

**Comment by CPyJIb** [comment]
http://kde-look.org/content/show.php?content=169085
I use this theme, looks pretty great

**Comment by varlesh** [comment]
Ok, i check this this style later, because very busy - port icons for apps to 24px and 16px sizes - 1300 icons o-0
