### ISSUE TITLE
Dark Version

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-suite#118]
@FadeMind Dark  Icon theme, LO icon theme,  not purged, because used with arc dark kde. Del plasma theme, aurorae, chromium theme, sddm and etc - because i don't like breeze style with dark colors. Dark papirus looks badly :(

**Comment by FadeMind** [comment]
@varlesh DONE

**Comment by FadeMind** [comment]
@varlesh https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=ebe1469f512d65dfb596639ce5161c04168b10c6

**Comment by varlesh** [comment]
@droserasprout
Please see compare dark with light
![breezeclementine](https://cloud.githubusercontent.com/assets/8083855/15656129/c837f63a-26ac-11e6-8878-6494bf4d7341.png)
![breezedarkclementine](https://cloud.githubusercontent.com/assets/8083855/15656130/c83a9d5e-26ac-11e6-98de-e32f57d0333e.png)
Maybe you like dark version, but it's realy looks bad with breeze style.
Also i delete Dark version because Breeze Dark GTK theme have another colors (not black) and i don't know GTK good :(

**Comment by beojan** [comment]
I liked the dark version. I don't understand what the problem you are talking about is.

It is hard to read the selected text in the dark screenshot, but that just means you need to set a dark selected text color to match the lighter selected background.

**Comment by varlesh** [comment]
No, it's style problem, not colors. Plasma 5 use Breeze as default, but dark version looking badly, because have very contrast strokes, with grey-blue-black stripes. I don't like this. You can compare engine Breeze with GTK or Oxygen for example:
![screenshot_20160601_161042](https://cloud.githubusercontent.com/assets/8083855/15710618/83fac0fc-2813-11e6-8546-c85fa1aff478.png)
![screenshot_20160601_160827](https://cloud.githubusercontent.com/assets/8083855/15710619/83fb4afe-2813-11e6-8bf7-554b60739074.png)
![screenshot_20160601_160457](https://cloud.githubusercontent.com/assets/8083855/15710620/83fe7c9c-2813-11e6-93b8-cfe464410050.png)

Papirus Dark now archived and discontinued!

**Comment by beojan** [comment]
I agree with you there, but that's just a consequence of the flat design idea.

I just use QtCurve with a very non-flat configuration, so Papirus Dark works very well for me. I think other people may also do this, so perhaps a warning not to use Papirus Dark with flat themes may be better than removing it entirely.

**Comment by varlesh** [comment]
Papirus Dark Archived, you can download and install it. But discontinued.
QtCurve will be added for Transparent and have problems too -  RED closetabs, bad radiobuttons and etc.. And QtCurve - this not main style for KDE and, not have GTK3 version!

**Comment by varlesh** [comment]
I proposed replacing - Arc Dark KDE.
https://github.com/varlesh/Arc-Dark-KDE

**Comment by varlesh** [comment]
If you like Papirus Dark version, please fork and developing.

**Comment by droserasprout** [comment]
@beojan and others, contact me if you want to continue development of dark flavour together and move it to 3.20. Also try Evolvere Dark for kvantum, it's cool replacement.

**Comment by beojan** [comment]
@droserasprout I saw your fork, but I've switched to arc-dark for now.

**Comment by silentzor** [comment]
@varlesh where's the archived version of Papirus Dark?

**Comment by varlesh** [comment]
@silentzor https://github.com/varlesh/papirus-suite/releases/tag/1.0

**Comment by silentzor** [comment]
Thanks. I see that you are splitting everything now, so instead of removing this why not split it and leave it unmaintained?
