### ISSUE TITLE
Sddm theme password autofocus

### ISSUE THREAD

**Issue by alexjp** [varlesh/papirus-suite#120]
Hi,

Trying out sddm theme of papirus, i cannot seem to get autofocus on the password field. Checking Main.qml it seems it should do password focus if login name is filled. It is filled.

Also, neight login field not password field get focus.

PS: dunno if it matters, but i have a multi monitor setup.

Thanks !

**Comment by varlesh** [comment]
Likely this bug sddm:
https://github.com/sddm/sddm/issues/197

**Comment by alexjp** [comment]
Well, I don't know for sure if it is that bug or not, but sddm with breeze theme does autofocus.

**Comment by alexjp** [comment]
ps: sorry for the late reply :(

**Comment by varlesh** [comment]
it's ok ) repo  moved to https://github.com/PapirusDevelopmentTeam
Fix added:
https://github.com/PapirusDevelopmentTeam/papirus-sddm-theme/commit/e01f12daf19f80d24687d4c8361e2977239aed64

**Comment by varlesh** [comment]
For easy using now:
```
cd /usr/share/sddm/themes/papirus
sudo rm Main.qml
sudo wget https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-sddm-theme/master/papirus/Main.qml
```

**Comment by alexjp** [comment]
Yep, confirm, its fixed :+1:
