### ISSUE TITLE
Papirus Development Team

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#123]
@varlesh can you make an Organization `Papirus Developement Team` on Github and add me and @horosgrisa?

I will care about Makefiles and PKGBUILD for Arch.

**Comment by varlesh** [comment]
Welcome

**Comment by FadeMind** [comment]
Begin here https://github.com/account/organizations/new @varlesh

**Comment by varlesh** [comment]
![screenshot_20160601_173237](https://cloud.githubusercontent.com/assets/8083855/15713364/dbd165e6-281e-11e6-9232-117a4cb07dbe.png)

**Comment by FadeMind** [comment]
`Papirus Development Team`

**Comment by varlesh** [comment]
https://github.com/orgs/PapirusDevelopmentTeam

**Comment by varlesh** [comment]
@FadeMind On Futere we need divide all themes, skins and etc. Also remake PKGBUILD's

**Comment by FadeMind** [comment]
@varlesh 
https://help.github.com/articles/repository-permission-levels-for-an-organization/
and
https://help.github.com/articles/managing-team-access-to-an-organization-repository/

**Comment by varlesh** [comment]
@FadeMind you owner. Sorry I'm busy now, port icons

**Comment by varlesh** [comment]
Later we need create many repos
papirus-icon-theme-kde
papirus-icon-theme-gtk
papirus-plasma-theme
and etc...

**Comment by FadeMind** [comment]
OK, So, I delete forked papirus-suite from you and I will create each part of papirus suite in separated repos.

**Comment by varlesh** [comment]
Yes )

**Comment by FadeMind** [comment]
@varlesh 
You need to configure your SSH agent for easy push comits (without promt password ANY TIME)


**1. Create a file:**

**$HOME/.config/systemd/user/ssh-agent.service**
```
[Unit]
Description=SSH key agent

[Service]
Type=forking
Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
ExecStart=/usr/bin/ssh-agent -a $SSH_AUTH_SOCK

[Install]
WantedBy=default.target
```

ENABLE and START service for USER:

```
systemctl --user enable ssh-agent;systemctl --user start ssh-agent
```

**2. Add value `SSH_ASKPASS` to `.bash_profile` file.**

$HOME/.bash_profile
```
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# additional local bin directory (based on my setup)
export PATH="${PATH}:/home/tomasz/bin"
# QT plugin path (based on my setup)
export QT_PLUGIN_PATH="/usr/lib/qt/plugins"
# set SSH_ASKPASS value
export SSH_ASKPASS="/usr/bin/ksshaskpass"
```


**3. edit file `$HOME/.ssh/config`**
```
IdentityFile ~/.ssh/id_rsa
User FadeMind # my user name -here paste yours
ForwardAgent yes
```
**4. Add to `.bashrc`
```
# Running ssh-agent after launch terminal
eval `ssh-agent -s` > /dev/null && ssh-add $HOME/.ssh/id_rsa $HOME/.ssh/id_rsa-aur </dev/null 1>&- 2>&-
```
Reload SH:
```
source .bashrc
```

Always after open new konsole window - new SSH agent AUTH will be done.
<hr/>

USE this simple script for download and access repos:

```
#!/bin/bash
SSH_ACCESS="git@github.com:PapirusDevelopmentTeam"
REPO=(papirus-yakuake-theme papirus-k3b-theme papirus-vlc-theme papirus-smplayer-theme papirus-sddm-theme papirus-qtcurve-theme papirus-plasma-theme papirus-look-and-feel papirus-konsole-colorscheme papirus-kmail-theme papirus-icon-theme-kde papirus-icon-theme-gtk papirus-gtk-theme papirus-color-scheme papirus-aurorae-theme libreoffice-papirus-theme bomi-skin-papirus)

for r in ${REPO[@]}
do 
    git clone $SSH_ACCESS/$r
done
```

**Comment by FadeMind** [comment]
DONE:
bomi-skin-papirus

**Comment by porkslapchop** [comment]
Sorry if offtopic. Does this mean I can install parts of the suite instead of using a script? On arch it pulls all dependencies.

**Comment by FadeMind** [comment]
@evilguc it is not offtopic ;)
Yep, I splitt papirus-suite repo for separated repo for EACH ONE part of it, Later I will splitt AUR packages and in final change code of papirus-git (and save only Meta Package data),

**Comment by porkslapchop** [comment]
@FadeMind Great Work! This suite is now far above the others on my list.

**Comment by FadeMind** [comment]
@varlesh  use this instead previous one.

```
#!/bin/bash
SSH_ACCESS="git@github.com:PapirusDevelopmentTeam"
REPO=(bomi-skin-papirus libreoffice-papirus-theme papirus-aurorae-theme papirus-color-scheme papirus-gtk-theme papirus-icon-theme-gtk papirus-icon-theme-kde papirus-k3b-theme papirus-kmail-theme papirus-konsole-colorscheme papirus-look-and-feel papirus-plasma-theme papirus-qtcurve-theme papirus-sddm-theme papirus-smplayer-theme papirus-vlc-theme papirus-wallpapers papirus-yakuake-theme)

for r in ${REPO[@]}
do 
    if [ ! -d "$r" ]; then
        git clone $SSH_ACCESS/$r
    else
        echo "DIR $r exists"
    fi
done
```

**Comment by FadeMind** [comment]
@varlesh Migration is FINISHED. I will care about PKGBUILD's tomorrow.

**Comment by varlesh** [comment]
@FadeMind Great job, big thx ) I'm port 250 icons only :(

**Comment by FadeMind** [comment]
@varlesh You have facebook? It would be good have contact via chat ;)

PS. Can you prepare small official Logo for Organization in a free time (size like avatar)

**Comment by varlesh** [comment]
@FadeMind  i rename some repos. Have only telegram @WarAlex
Yes, logo available on future...
