### ISSUE TITLE
[kate] [idea] Add kateschema themes files for kate

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#70]
Looking here: https://github.com/FadeMind/archbash/tree/master/kate.schema

Theming based on global papirus colors.
Maybe You can add them as official part of papirus? 
BUT IDK jet where to put this files for global available in the system. Probably user need manualy import themes using in the Kate app.
@varlesh

**Comment by varlesh** [comment]
Good idea :+1: 
I not use KDE now and check this schemes.  You can show screens with document (svg or other)?

PS: I previously used Kubuntu, but lately it works badly and not updated.
Need install Arch, but I am too lazy and not enough time ))

**Comment by FadeMind** [comment]
@varlesh 
![screenshot_20151215_133344](https://cloud.githubusercontent.com/assets/9846948/11810798/2e4611f0-a331-11e5-934d-81ad15fa0137.png)
![screenshot_20151215_133432](https://cloud.githubusercontent.com/assets/9846948/11810794/2dd9ced2-a331-11e5-8d20-69b4a4f334c6.png)
![screenshot_20151215_133704](https://cloud.githubusercontent.com/assets/9846948/11810795/2ddb0770-a331-11e5-8597-642886527b5d.png)
![screenshot_20151215_133733](https://cloud.githubusercontent.com/assets/9846948/11810796/2de0e528-a331-11e5-86b4-223e7a69df9d.png)
![screenshot_20151215_133820](https://cloud.githubusercontent.com/assets/9846948/11810797/2de48642-a331-11e5-9c1e-b360e42a164b.png)
<hr/>
![screenshot_20151215_134228](https://cloud.githubusercontent.com/assets/9846948/11810847/b689b8e6-a331-11e5-8a53-1b05c3462dbf.png)
![screenshot_20151215_134319](https://cloud.githubusercontent.com/assets/9846948/11810858/d6df3a26-a331-11e5-9f1f-856966da46a0.png)
![screenshot_20151215_134429](https://cloud.githubusercontent.com/assets/9846948/11810877/fd0258b4-a331-11e5-81ab-d97df4e2ba92.png)

**Comment by varlesh** [comment]
3 screen - green color merge with grey (selected)
5 screen - orange very saturated and bright
8 screen (last) - red very saturated and bright
8 screen (last) - text font (grey) faded

**Comment by varlesh** [comment]
also yelow on light scheme need subtract saturation

**Comment by varlesh** [comment]
Note: Konsole color schemes create with support Solarized. You can use other colors for better looking.

**Comment by varlesh** [comment]
For example this colors:
https://github.com/varlesh/papirus-pack-kde/blob/master/konsole-colorschemes/papirus-dark.png
https://github.com/varlesh/papirus-pack-kde/blob/master/konsole-colorschemes/papirus.png
Use kcolorchooser

**Comment by varlesh** [comment]
@horosgrisa Hi :) 
I think need create 4 colors schemes for Konsole, because some users not use Solarized style.
For example available:
Papirus.colorscheme
Papirus Solarized.colorscheme
Papirus Dark.colorscheme
Papirus Dark Solarized.colorscheme
As you look at this?

**Comment by FadeMind** [comment]
@varlesh  Use names without spaces.

**Comment by varlesh** [comment]
@FadeMind It does not matter

**Comment by varlesh** [comment]
@horosgrisa Papirus Solarized it will be difficult to adapt the likely. Maybe not needed, only Dark version.

**Comment by FadeMind** [comment]
@varlesh where install colorscheme files?

**Comment by varlesh** [comment]
For Konsole:
~/.local/share/konsole/ or /usr/share/konsole/

**Comment by FadeMind** [comment]
@varlesh  I thought you wrote schemes for kate.
My faux pas. ;)

**Comment by varlesh** [comment]
Uf...
I found only /usr/share/config/kateschemarc
