### ISSUE TITLE
[GTK] Problem with Firefox side panel on Papirus Dark

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-suite#72]
Side panel edging #353535
I don't know how fix it :(
Scrollbar covers this edging and looking badly.
![7](https://cloud.githubusercontent.com/assets/8083855/11839608/384cb012-a400-11e5-919f-c8cfe29e6de4.png)![8](https://cloud.githubusercontent.com/assets/8083855/11839609/384e44cc-a400-11e5-8013-e5b3003983d6.png)

**Comment by FadeMind** [comment]
@varlesh  Related: https://github.com/dirruk1/gnome-breeze/issues/46#issuecomment-165491335

**Comment by varlesh** [comment]
Fixed 7ae5015ca94cd5a31f62a1315ec150f013a3ef28
