### ISSUE TITLE
[additional] Dropbox status icon fix, copycom tray fix

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#79]
I prepared dropbox icons based on papirus svg files (with proper sizes). 

ZIP file: [dropbox-papirus.zip](https://github.com/varlesh/papirus-pack-kde/files/72139/dropbox-papirus.zip)
see `INSTALL.bash` file code.
<hr/>
Copy com file storage papirus icon color (SVG)
[copy.svg.zip](https://github.com/varlesh/papirus-pack-kde/files/72141/copy.svg.zip)

target:
`/usr/share/icons/hicolor/scalable/apps/copy.svg`

Looking:
![screenshot_20151225_113741](https://cloud.githubusercontent.com/assets/9846948/12002342/ed25f6ae-aafb-11e5-96ac-797bed999f07.png)

@varlesh

**Comment by varlesh** [comment]
DropBox blured

**Comment by FadeMind** [comment]
@varlesh  dropbox using PNG files 16 and 22 px and SNI Proxy have issues with PNG rendering.

**Comment by varlesh** [comment]
Ok, need dark version too. 
Also "copy" have stroke (do you remember inkscape bug - view on dolphin)
