### ISSUE TITLE
[qtcurve] [fix] honor SVG icon files names extension in GTK apps

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#86]
@varlesh  ;)
QtCurve in first setup create a big one file named `gtk-icons` which contents all known GTK icons. Sadly looking for PNG files and against papirus icons it using oxygen legacy icon theme/gnome icon theme.
FIX:
1. Set QtCurve as theme for GTK2 apps.
2. Launch any GTK2 apps for a while and close it.
3. In terminal launch command:
`sed -i 's/png/svg/g' $HOME/.config/qtcurve/gtk-icons`
For **root** you need copy files:
`cd  $HOME/.config/qtcurve/ && sudo cp -R * /root/.config/qtcurve/`
Aaand....
![s](http://cdn.meme.am/instances/56367652.jpg)
<br/>

**BEFORE**
![screenshot_20160117_134224](https://cloud.githubusercontent.com/assets/9846948/12377484/2f05cda2-bd20-11e5-8df5-d78d051537b2.png)
**AFTER**
![screenshot_20160117_134637](https://cloud.githubusercontent.com/assets/9846948/12377499/c13f6156-bd20-11e5-96cc-a2cf74e22b2e.png)

**Comment by varlesh** [comment]
Thx, but how change tab close button?
![screenshot_20160117_163748](https://cloud.githubusercontent.com/assets/8083855/12377745/bd73a060-bd38-11e5-92ca-e6f8c29ef5ca.png)

**Comment by FadeMind** [comment]
@varlesh IDK. QtCurve is little bit OOD and using old schemas (target KDE3  and KDE4). Some times ago GTK3 porting was dropped by developers.
