### ISSUE TITLE
LibreOffice Theme is out-of-date

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#91]
@varlesh 
compare:
Sifr:
![screenshot_20160210_200037](https://cloud.githubusercontent.com/assets/9846948/12958232/fb133420-d030-11e5-867c-9a0a746ca9a1.png)

with

Papirus:

![screenshot_20160210_200200](https://cloud.githubusercontent.com/assets/9846948/12958283/31b33548-d031-11e5-93dc-a9f4878c1bc7.png)

**NOTE: In  menus are options whos using legacy bad looking icon when papirus theme is set.
Sifr in backend using Breeze icons.**

**Comment by FadeMind** [comment]
Not all entries are honored:
**PAPIRUS**
![screenshot_20160212_103911](https://cloud.githubusercontent.com/assets/9846948/13003352/7301e572-d175-11e5-9ae3-534110d17321.png)
**SIFR**
![screenshot_20160212_103704](https://cloud.githubusercontent.com/assets/9846948/13003328/540272cc-d175-11e5-91b4-bfa3e7360ea3.png)
<hr/>
**PAPIRUS**
![screenshot_20160212_103923](https://cloud.githubusercontent.com/assets/9846948/13003399/a1c37c54-d175-11e5-9039-d62159deaccb.png)
**SIFR**
![screenshot_20160212_103720](https://cloud.githubusercontent.com/assets/9846948/13003367/8798d810-d175-11e5-80a7-f76f6390609c.png)
<hr/>
**PAPIRUS**
![screenshot_20160212_103931](https://cloud.githubusercontent.com/assets/9846948/13003458/f7a310da-d175-11e5-8cc9-86b139a76e1e.png)
**SIFR**
![screenshot_20160212_103735](https://cloud.githubusercontent.com/assets/9846948/13003474/0832ee66-d176-11e5-8f10-249cf0cc368d.png)
<hr/>
**PAPIRUS**
![screenshot_20160212_103953](https://cloud.githubusercontent.com/assets/9846948/13003591/bfe42aa2-d176-11e5-82bf-57134f9be269.png)
**SIFR**
![screenshot_20160212_103759](https://cloud.githubusercontent.com/assets/9846948/13003594/d1b92e30-d176-11e5-8023-338f7d68b608.png)
<hr/>
**PAPIRUS**
![screenshot_20160212_104004](https://cloud.githubusercontent.com/assets/9846948/13003572/9a9517fc-d176-11e5-9e91-bb2e5796d737.png)
**SIFR**
![screenshot_20160212_103813](https://cloud.githubusercontent.com/assets/9846948/13003559/84e17838-d176-11e5-9c50-092b0f9b2405.png)
<hr/>
**PAPIRUS**
![screenshot_20160212_104029](https://cloud.githubusercontent.com/assets/9846948/13003610/f5ba6d12-d176-11e5-9a92-409905985ecc.png)
**SIFR**
![screenshot_20160212_104049](https://cloud.githubusercontent.com/assets/9846948/13003614/fa4e4a74-d176-11e5-9c17-40bdd8ba865b.png)

@varlesh

**Comment by varlesh** [comment]
libreoffice have over 2000 icons - it's very hard create and porting. 
Ican't port Full theme now.
imagemagick bad working with some PNG's. (alpha channel not working, many icons not invert colors and etc)
We need find missing icons and port them - is the best variant.

**Comment by varlesh** [comment]
Why close?
We need find some icons names and add...

**Comment by varlesh** [comment]
@FadeMind I found problem. Some icons have symlinks on **links.txt**.
For example:
Papirus:
```
cmd/lc_absoluterecord.png cmd/lc_helpindex.png
cmd/lc_accepttrackedchange.png cmd/lc_ok.png
cmd/lc_adddatefield.png cmd/lc_datefield.png
cmd/lc_addons.png cmd/lc_insertplugin.png
cmd/lc_addprintarea.png cmd/lc_inserttable.png
cmd/lc_addtable.png cmd/lc_inserttable.png
cmd/lc_adjust.png cmd/lc_zoomoptimal.png
```
Breeze:
```
cmd/lc_basicshapes.block-arc.png cmd/lc_arc.png
cmd/lc_basicshapes.circle-pie.png cmd/lc_pie.png
cmd/lc_basicshapes.circle.png cmd/lc_circle.png
cmd/lc_basicshapes.ellipse.png cmd/lc_ellipse.png
cmd/lc_basicshapes.frame.png cmd/lc_rect_unfilled.pn
``

**Comment by FadeMind** [comment]
Maybe using `links.txt` FROM zifr in papirus?

**Comment by varlesh** [comment]
No, because themes different (cmd):
Papirus - 1633 icons
Breeze - 1378 icons
Sifr - 934 icons
This very drudgery (

**Comment by FadeMind** [comment]
Easy way:
donwload sources of breeze and change blue to gray. Create next png based them via `Makefile` script available on: 
https://github.com/NitruxSA/breeze-icon-theme/tree/master/LibreOffice_Breeze

**Comment by varlesh** [comment]
I use Unity DE now and icons from menu not showing - that problem to.
![2016-02-14 20-58-25](https://cloud.githubusercontent.com/assets/8083855/13035305/b9026828-d35d-11e5-9b6a-1b74febf49a0.png)

**Comment by varlesh** [comment]
Makefile not variant because Breeze have 1378 icons, but Papirus have 1633 icons. We need fond  missing icons and add symlinks to **links.txt**

**Comment by varlesh** [comment]
I think later how faster and better solve problem. 
PS: legacy icons Tango:
https://launchpad.net/~libreoffice/+archive/ubuntu/libreoffice-5-1/+files/libreoffice-style-tango_5.1.0~rc3-0ubuntu1~wily0_all.deb
