### ISSUE TITLE
WARNING! REBUILD and RENAME REPO

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-suite#92]
I rebuild repo for all DE. Need change PKGBUILD's.
These packages should not depend on Plasma (because compatible with other DE to):
libreooffice
bomi-skin
smplayer-skin
vlc-skin
gtk-icon-theme

@horosgrisa 
@FadeMind

**Comment by FadeMind** [comment]
@varlesh 

https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=8aad6229d9d004e44d5562862ea484dc206af813

**Comment by varlesh** [comment]
@FadeMind papirus-git meta install depend papirus-gtk-icon-theme-git papirus-icon-theme-git  - it's not properly

**Comment by varlesh** [comment]
For KDE papirus-gtk-icon-theme-git not needed and for GTK papirus-icon-theme-git not needed

**Comment by FadeMind** [comment]
@varlesh  so, what should be depend installed and as optional then?

code:

package_papirus-git() {
    depends=('papirus-plasma-theme-git' 
             'papirus-icon-theme-git' 
             'papirus-gtk-icon-theme-git'
             'papirus-color-scheme-git' 
             'papirus-gtk-theme-git' 
             'papirus-aurorae-theme-git' 
             'papirus-qtcurve-theme-git' 
             'papirus-konsole-colorscheme-git')
    optdepends=("papirus-yakuake-theme-git: Papirus theme for Yakuake" 
                "bomi-skin-papirus-git: Papirus theme for Bomi" 
                "libreoffice-papirus-theme-git: Papirus theme for LibreOffice" 
                "papirus-kmail-theme-git: Papirus theme for KMail" 
                "papirus-vlc-theme-git: Papirus theme for VLC Media Player" 
                "papirus-k3b-theme-git: Papirus theme for K3B" 
                "papirus-smplayer-theme-git: Papirus theme for SMPlayer")
    install -dm755 ${pkgdir}/usr/share/plasma/look-and-feel
    cp -r ${srcdir}/${_pkgname}/kde-pack/look-and-feel/* ${pkgdir}/usr/share/plasma/look-and-feel/
    find "${pkgdir}" -type f -exec chmod 644 {} +
    find "${pkgdir}" -type d -exec chmod 755 {} +
}

**Comment by varlesh** [comment]
No, maybe will be better create meta for KDE and separate ащк GTK?

**Comment by varlesh** [comment]
Or meta not needed any more.

**Comment by FadeMind** [comment]
Infact:
papirus-git is target for KDE (deps all AND install look and feel for plasma 5

Who's using other DE, can install packages separelly (just icons for example.

Basic question:
what is difference between papirus-icon-theme and GTK icon theme only?

Should I mark `papirus-gtk-icon-theme-git` as optional dep?

**Comment by varlesh** [comment]
Icons for GTK difference with KDE. GTK icons have other tray icons and style (Paper source - white), but KDE icons have transparent icons.
@horosgrisa please help us

**Comment by FadeMind** [comment]
@varlesh OK. I do that:
- removing from deps/opt deps 'papirus-gtk-icon-theme-git'.
https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=abf86fdb41582028e155e9d2252da7e0ee919125
And in results;
anyone can install just 'papirus-gtk-icon-theme-git'

papirus-git is target for KDE Plasma 5.
All are happy :+1:

**Comment by varlesh** [comment]
papirus-gtk-icon-theme-git realy not needed for KDE.
And papirus-gtk-theme need rename to papirus-kde-gtk-theme, because user will be confused ))

**Comment by varlesh** [comment]
And maybe need rename papirus-git to papirus-kde-git

**Comment by FadeMind** [comment]
@varlesh IMO is not needed. IF I will renaming to another `basename`, then TU Arch AUR will removing current papirus-git (after request) whole package and I will need to create a new repo in aur. This is not easy as look like.

**Comment by varlesh** [comment]
I dont know how better... But AUR have lost of packages

**Comment by FadeMind** [comment]
Was updated to a new sources. Fixed dependencies. The case was made.

@varlesh  you mean LOTS...? :>

AUR have ONE basename with lots of sub-packages, and can be easy extended with  another one. EASY AS FK ;)

**Comment by varlesh** [comment]
Sorry my English )
More packages - users confused. Maybe delete papirus branch, but continue git version - papirus-git

**Comment by varlesh** [comment]
we wait @horosgrisa

**Comment by varlesh** [comment]
@FadeMind Little change description for papirus:
Papirus color scheme for KDE
Look-and-feel package for Papirus KDE
and etc...
Papirus have more changes from Paper

**Comment by varlesh** [comment]
@horosgrisa Возможно стоит удалить какую-либо версию с аура, как вы считаете? Много пакетов - пользователи будут путаться. Не вижу смысла дублировать пакеты papirus  и papirus-git.

**Comment by FadeMind** [comment]
@varlesh https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=65b80505cf95108dd80f03882a6ae28fb68a81a0

**Comment by varlesh** [comment]
@FadeMind Very Good! Thx )

**Comment by varlesh** [comment]
@FadeMind Maybe rename some packages?
smplayer-theme-papirus
libreoffice-style-papirus

![2016-02-13 16-44-35](https://cloud.githubusercontent.com/assets/8083855/13027939/1fd05c1a-d271-11e5-900a-079caf8b8b95.png)
![2016-02-13 16-45-40](https://cloud.githubusercontent.com/assets/8083855/13027943/3e09a4c0-d271-11e5-92f4-7ddecaa966ba.png)

**Comment by horosgrisa** [comment]
@varlesh Тема для Chrome находится в папке тем для KDE

**Comment by horosgrisa** [comment]
Я не буду удалять пакеты papirius-* т.к. они в отличии от пакетов *-git стабильные.

**Comment by varlesh** [comment]
@horosgrisa Тема для Chrome не входит не в один из пакетов и предназначена исключительно для стиля плазмы Papirus Dark.
Касательно пакетов, то не понимаю в чем выражается стабильность, ведь они же все с гита, релизов тут нет.
Я не хочу кого-либо обидеть и ценю участие и труд каждого, просто пользователям так будет удобней и проще ориентироваться.
Пока я указал пакеты FadeMind, потому как они уже поправлены...

**Comment by horosgrisa** [comment]
@varlesh Пакеты без приставки -git берутся из определенного коммита, а -git пакеты из HEAD, и предугадать как меняется структура репозитория невозможно, поэтому такой пакет (если его не обновлять постоянно) потенциально нестабилен. Это разделение на пакеты с -git и без -git для Arch нормально. Но я все-таки реструктурирую пакеты.

**Comment by FadeMind** [comment]
@varlesh @horosgrisa 
`papirus` STABLE non bleedy edge git releases are SAFE for end users. Sometimes new commit = some issues, missing, etc.
Renaming packages = create new conflicts in PKGBUILD code and force replacing (complications for end users). IMO not needed.

GTK theme can be used in non KDE DE so, You can add install note for  `papirus-gtk-theme-git`

**Comment by varlesh** [comment]
@FadeMind No, GTK not use on GTK DE - this theme only for KDE!
@horosgrisa Ok, i wait your info and update README

**Comment by varlesh** [comment]
Sorry guys, i dont know GTK and theme - only port Breeze theme.
For GTK better use Arc or Vertex themes.

**Comment by horosgrisa** [comment]
@varlesh 
Stable packages for Arch and others:
for KDE:
`yaourt -S papirus-icon-theme-kde papirus-gtk-theme papirus-look-and-feel plasma-theme-papirus papirus-color-scheme papirus-qtcurve-theme papirus-aurorae-theme yakuake-skin-papirus papirus-konsole-colorscheme papirus-kmail-theme`
for Gnome and others GTK-based:
`yaourt -S papirus-icon-theme-gtk`
for other apps:
`yaourt -S bomi-skin-papirus vlc-skin-papirus libreoffice-style-papirus`

**Comment by FadeMind** [comment]
@horosgrisa You are not consequent.

pkgdesc="**Papirus theme** for K3B" 

is correct, but in other places is Paper

tomasz@arch ~]$ ccat PKGBUILD\?h\=papirus |grep Paper
    pkgdesc="Meta-package for modified and adaptive Paper theme"
        'papirus-icon-theme-gtk: Modified and adaptive gtk Paper icon theme for Gnome'
        'papirus-icon-theme-kde: Modified and adaptive Paper icon theme for KDE'
        'papirus-gtk-theme: Modified and adaptive Paper gtk theme'
        'papirus-look-and-feel: Look-and-feel package for modified and adaptive Paper theme for KDE.'
        'plasma-theme-papirus: Modified and adaptive Paper plasma theme for KDE'
        'papirus-color-scheme: Modified and adaptive Paper color scheme for KDE'
        'papirus-qtcurve-theme: Modified and adaptive Paper decorations for QtCurve'
        'papirus-aurorae-theme: Modified and adaptive Paper decorations for Kwin'
        'yakuake-skin-papirus: Modified and adaptive Paper skin for Yakuake'
        'papirus-konsole-colorscheme: Modified and adaptive Paper colorscheme for Konsole'
        'papirus-kmail-theme: Modified and adaptive Paper theme for Kmail'
        'vlc-skin-papirus: Paper skin for VLC Media Player'
    pkgdesc="Modified and adaptive gtk Paper icon theme for Gnome"
    pkgdesc="Modified and adaptive Paper icon theme for KDE"
    pkgdesc="Modified and adaptive Paper gtk theme"
    pkgdesc="Look-and-feel package for modified and adaptive Paper theme for KDE."
    pkgdesc="Modified and adaptive Paper color scheme for KDE"
    pkgdesc="Modified and adaptive Paper decorations for QtCurve"
    pkgdesc="Modified and adaptive Paper decorations for Kwin"
    pkgdesc="Modified and adaptive Paper skin for Yakuake"
    pkgdesc="Modified and adaptive Paper colorscheme for Konsole"
    pkgdesc="Modified and adaptive Paper theme for Kmail"
    pkgdesc="Paper skin for VLC Media Player"
[tomasz@arch ~]$

**Comment by horosgrisa** [comment]
@FadeMind Oops..

**Comment by varlesh** [comment]
Big thx guys :)

**Comment by FadeMind** [comment]
@varlesh 
BIG refactoring PKGBUILD:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=papirus-git

commits: https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=95ab00c07adcdd5119031d7bac95e83e5baf4413
