### ISSUE TITLE
Transmission tray icon

### ISSUE THREAD

**Issue by Israphel** [varlesh/papirus-suite#93]
Can we have a "mono" tray icon for transmission? just like Clementine has one

![screenshot_20160213_153124](https://cloud.githubusercontent.com/assets/720191/13029287/e2a45774-d266-11e5-81ee-a3ce7ad50113.png)

**Comment by varlesh** [comment]
Yes, on Plasma used monochrome icons. But for transmission icons already available (as symlink ktorrent):
https://github.com/varlesh/papirus-suite/blob/master/kde-pack/icons/papirus-dark/16x16/apps/transmission.svg
https://github.com/varlesh/papirus-suite/blob/master/kde-pack/icons/papirus-dark/16x16/apps/transmission-panel.svg

**Comment by FadeMind** [comment]
@varlesh lastest qbittorrent does not honor papirus icon tray anymore BTW.

**Comment by varlesh** [comment]
@horosgrisa What icon use for qBittorrent. Please show screen
@Israphel I add transmission-qt symlink, please check

**Comment by FadeMind** [comment]
@varlesh 
![screenshot_20160213_200745](https://cloud.githubusercontent.com/assets/9846948/13029465/75a5cbfe-d28d-11e5-87e5-a559e13763f2.png)




[tomasz@arch ~]$ pacman -Ql qbittorrent 
qbittorrent /usr/
qbittorrent /usr/bin/
qbittorrent /usr/bin/qbittorrent
qbittorrent /usr/share/
qbittorrent /usr/share/appdata/
qbittorrent /usr/share/appdata/qBittorrent.appdata.xml
qbittorrent /usr/share/applications/
qbittorrent /usr/share/applications/qBittorrent.desktop
qbittorrent /usr/share/icons/
qbittorrent /usr/share/icons/hicolor/
qbittorrent /usr/share/icons/hicolor/128x128/
qbittorrent /usr/share/icons/hicolor/128x128/apps/
qbittorrent /usr/share/icons/hicolor/128x128/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/16x16/                                                                                                 
qbittorrent /usr/share/icons/hicolor/16x16/apps/                                                                                            
qbittorrent /usr/share/icons/hicolor/16x16/apps/qbittorrent.png                                                                             
qbittorrent /usr/share/icons/hicolor/192x192/                                                                                               
qbittorrent /usr/share/icons/hicolor/192x192/apps/                                                                                          
qbittorrent /usr/share/icons/hicolor/192x192/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/22x22/
qbittorrent /usr/share/icons/hicolor/22x22/apps/
qbittorrent /usr/share/icons/hicolor/22x22/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/24x24/
qbittorrent /usr/share/icons/hicolor/24x24/apps/
qbittorrent /usr/share/icons/hicolor/24x24/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/32x32/
qbittorrent /usr/share/icons/hicolor/32x32/apps/
qbittorrent /usr/share/icons/hicolor/32x32/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/36x36/
qbittorrent /usr/share/icons/hicolor/36x36/apps/
qbittorrent /usr/share/icons/hicolor/36x36/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/48x48/
qbittorrent /usr/share/icons/hicolor/48x48/apps/
qbittorrent /usr/share/icons/hicolor/48x48/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/64x64/
qbittorrent /usr/share/icons/hicolor/64x64/apps/
qbittorrent /usr/share/icons/hicolor/64x64/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/72x72/
qbittorrent /usr/share/icons/hicolor/72x72/apps/
qbittorrent /usr/share/icons/hicolor/72x72/apps/qbittorrent.png
qbittorrent /usr/share/icons/hicolor/96x96/
qbittorrent /usr/share/icons/hicolor/96x96/apps/
qbittorrent /usr/share/icons/hicolor/96x96/apps/qbittorrent.png
qbittorrent /usr/share/licenses/
qbittorrent /usr/share/licenses/qbittorrent/
qbittorrent /usr/share/licenses/qbittorrent/COPYING
qbittorrent /usr/share/man/
qbittorrent /usr/share/man/man1/
qbittorrent /usr/share/man/man1/qbittorrent.1.gz
qbittorrent /usr/share/pixmaps/
qbittorrent /usr/share/pixmaps/qbittorrent.png
[tomasz@arch ~]$ ccat /usr/share/applications/qBittorrent.desktop
[Desktop Entry]
Categories=Network;FileTransfer;P2P;Qt;
Exec=qbittorrent %U
GenericName=BitTorrent client
Comment=Download and share files over BitTorrent
Icon=qbittorrent
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
Name=qBittorrent
Terminal=false
Type=Application
StartupNotify=false
StartupWMClass=qbittorrent

**Comment by varlesh** [comment]
@FadeMind On settings qbittorrent It was previously available option to select icons of style
![2016-02-13 22-15-12](https://cloud.githubusercontent.com/assets/8083855/13029494/4f7a2f8a-d29f-11e5-8c3c-9b6271dcfd65.png)

**Comment by FadeMind** [comment]
I know. sorry I forgot change this:
![screenshot_20160213_201712](https://cloud.githubusercontent.com/assets/9846948/13029508/db6a5472-d28e-11e5-82b2-b6bf670596e7.png)

**Comment by FadeMind** [comment]
qbittorent use big icon instead of small monocored

**Comment by varlesh** [comment]
For tray apps used this style:
[16x16/apps]
Context=Applications
Size=16
MinSize=16
MaxSize=24
If manualy delete 32x32/apps/qbittorrent.svg - use monochrome icon?

**Comment by varlesh** [comment]
Or other solution - reduce plassma panel vertical size to 24 px.

**Comment by Israphel** [comment]
@varlesh sorry I still see the transmission icon on the systray, not the ktorrent one

**Comment by FadeMind** [comment]
@varlesh removing icons don't fix issue. Scalling panel too.

**Comment by varlesh** [comment]
@Israphel i download transmission-qt and packace available only transmission-qt.png icon
But symlinks already added
![2016-02-14 00-19-38](https://cloud.githubusercontent.com/assets/8083855/13030134/eea967cc-d2b0-11e5-970a-a84e80e1403d.png)
Maybe transmission-qt use binary icons for tray

**Comment by varlesh** [comment]
I dont know why qbittorrent and transmission not use this icons. You see copyq, clementine-panel and others working...

**Comment by varlesh** [comment]
@Israphel Also i find this bug:
https://trac.transmissionbt.com/ticket/5848

**Comment by Israphel** [comment]
I see them but sadly not working.

My GF uses transmission-gtk and it does respect the icon theme. Maybe the problem is transmission-qt.

![screenshot_20160213_183005](https://cloud.githubusercontent.com/assets/720191/13030189/10ed6562-d280-11e5-9432-585de4e44621.png)

**Comment by Israphel** [comment]
So they fixed on 2.90? I'm on 2.84

**Comment by varlesh** [comment]
Yes this fixed on 2.90 or patch from yourself.
But i add "transmission-tray-icon" from the future

**Comment by varlesh** [comment]
@FadeMind You can use binary monochrome icon. I dont know how fix this :(

**Comment by Israphel** [comment]
Icon works ok with the patch. Thanks.
![screenshot_20160213_191419](https://cloud.githubusercontent.com/assets/720191/13030352/03724a78-d286-11e5-9731-98008051147d.png)

**Comment by varlesh** [comment]
Fine :+1:
