### ISSUE TITLE
Dependencies not installable ppa

### ISSUE THREAD

**Issue by cgklein** [varlesh/papirus-suite#94]
In Linux Mint 17.3 papirus-pack-kde4 will not install.

papirus-pack-kde4:
 Depends: plasma-workspace  but it is not installable

**Comment by varlesh** [comment]
Thx for contributing, i change depend "plasma-workspace" to "plasma-desktop". Package updated, please check:
https://launchpad.net/~varlesh-l/+archive/ubuntu/papirus-pack/+build/9014904/+files/papirus-pack-kde4_2016.02.15_all.deb

**Comment by cgklein** [comment]
Working now, thanks for fast fix.
