### ISSUE TITLE
Dashboard icon

### ISSUE THREAD

**Issue by netforhack** [varlesh/papirus-suite#95]
![](http://i.imgur.com/ILZijlu.jpg)

Ubuntu 15.10
`unity --version`
`unity 7.3.3`

Но у тебя другая иконка...
![](https://raw.githubusercontent.com/varlesh/papirus-suite/master/papirus-arc-unity.png)

**Comment by varlesh** [comment]
```
cd /usr/share/icons/Papirus-GTK/48x48/apps
sudo cp launcher_bfb.png /usr/share/unity/icons/
gtk-update-icon-cache
```

**Comment by inpr1se** [comment]
:laughing:
