### ISSUE TITLE
smplayer-themes

### ISSUE THREAD

**Issue by cgklein** [varlesh/papirus-suite#96]
smplayer-themes not working on mint 17.3
Not sure how the .rcc file works.
Other smplayer-themes use .png files, one for each icon.

**Comment by varlesh** [comment]
Yes, it's skin for new version. You can update version from ppa:
https://launchpad.net/~rvm/+archive/ubuntu/smplayer
Or install manually:
[smplayer-themes-old.zip](https://github.com/varlesh/papirus-suite/files/132898/smplayer-themes-old.zip)

**Comment by varlesh** [comment]
Also i update packages soon, thx for contributing.

**Comment by varlesh** [comment]
https://launchpad.net/~varlesh-l/+archive/ubuntu/papirus-pack/+build/9020883/+files/smplayer-skin-papirus_2016.02.16ubuntu14.04fix_all.deb

**Comment by cgklein** [comment]
Thanks for your help, both solutions work.
