### ISSUE TITLE
[icon request] Page Layout Programs

### ISSUE THREAD

**Issue by cgklein** [varlesh/papirus-suite#97]
Please add Scribus and Master PDF icons.

**Comment by varlesh** [comment]
please show icon name
open on text editor /usr/share/applications/APP.desktop and  find:
icon=

**Comment by FadeMind** [comment]
@cgklein @varlesh 
Scribus and Master PDF is already included in papirus icon theme. Looking in apps dir.

**Comment by cgklein** [comment]
(scribus.desktop) and (masterpdfeditor3.desktop)

**Comment by FadeMind** [comment]
![screenshot_20160216_210710](https://cloud.githubusercontent.com/assets/9846948/13089507/41ffac82-d4f1-11e5-8c87-ccf4f7de6973.png)

**Comment by FadeMind** [comment]
@varlesh Scribus is missing

**Comment by varlesh** [comment]
@cgklein open scribus.desktop and show **icon=**

**Comment by varlesh** [comment]
@FadeMind you shure pdfeditor icon Master PDF?

**Comment by cgklein** [comment]
Icon=/opt/master-pdf-editor-3/masterpdfeditor3.png and Icon=scribus

**Comment by FadeMind** [comment]
@varlesh https://github.com/varlesh/papirus-suite/issues/47


And devs fixed desktop file in lastest scribus yaay

[tomasz@arch ~]$ cat /usr/share/applications/scribus.desktop
[Desktop Entry]
Name=Scribus
Type=Application
**Icon=scribus**
Comment=Page Layout and Publication
Comment[ar]=سكريبس
Comment[fa]=اسکریباس
#Comment[lo]=ສະຄຣີບັດສ໌
Comment[ta]=ஸ்கிரிபஸ்
Comment[af]=Werkskerm Publisering
Comment[bg]=Издателска програма
Comment[bs]=Stono izdavaštvo (DTP)
Comment[ca]=Publicació d'escriptori
Comment[cs]=Publikační systém (DTP)
Comment[cy]=Cyhoeddi Penbwrdd
Comment[da]=Dtp
Comment[eo]=DTP-programo
Comment[es]=Publicación de escritorio                                                                                                       
Comment[et]=Küljendusrakendus                                                                                                               
#Comment[fa]=نشر میزکار                                                                                                                     
Comment[fi]=Julkaisuohjelma                                                                                                                 
Comment[fr]=Publication assistée par ordinateur (PAO)                                                                                       
Comment[he]=הוצאה לאור שולחנית
Comment[hr]=Stolno izdavaštvo
Comment[hu]=Kiadványszerkesztés
Comment[it]=Pubblicazioni
Comment[ja]=デスクトップパブリッシング
Comment[lo]=ເດດທອບພັລບບີດຊິງ
Comment[lt]=Darbastalio leidykla
Comment[nb]=Datatrykkeprogram
Comment[nn]=Datatrykk
Comment[nso]=Kwalakwatso ya Desktop
Comment[pl]=Program do składu tekstu
Comment[pt]=Edição electrónica
Comment[pt_BR]=Editoração eletrônica
Comment[ru]=Настольное издательство
Comment[sl]=Namizno založništvo
Comment[sr]=Стоно издаваштво
Comment[ss]=Kushicelela ku desktop
Comment[sv]=Desktop Publishing
Comment[th]=เดสก์ทอปพับลิชชิง
Comment[tr]=Masaüstü Yayıncılık
Comment[uk]=Видавнича система
Comment[uz]=Кичик нашриёт
Comment[ven]=U andadza Desikithopo
Comment[xh]=Upapasho lwe Desktop
Comment[zh_CN]=桌面出版
Comment[zh_TW]=桌面出版
Comment[zu]=Ukushicilelwa kwe-Desktop
#Comment[ru]=Настольная издательская система
GenericName=Page Layout (Development)
GenericName[af]=Werkskerm Publisering
GenericName[bg]=Издателска програма
GenericName[bs]=Stono izdavaštvo (DTP)
GenericName[ca]=Publicació d'escriptori
GenericName[cs]=Publikační systém (DTP)
GenericName[cy]=Cyhoeddi Penbwrdd
GenericName[da]=Dtp
GenericName[eo]=DTP-programo
GenericName[es]=Publicación de escritorio
GenericName[et]=Küljendusrakendus
GenericName[fa]=نشر میزکار
GenericName[fi]=Julkaisuohjelma
GenericName[fr]=Publication assistée par ordinateur (PAO)
GenericName[he]=הוצאה לאור שולחנית
GenericName[hr]=Stolno izdavaštvo
GenericName[hu]=Kiadványszerkesztés
GenericName[it]=Pubblicazioni
GenericName[ja]=デスクトップパブリッシング
GenericName[lo]=ເດດທອບພັລບບີດຊິງ
GenericName[lt]=Darbastalio leidykla
GenericName[nb]=Datatrykkeprogram
GenericName[nn]=Datatrykk
GenericName[nso]=Kwalakwatso ya Desktop
GenericName[pl]=Program do składu tekstu
GenericName[pt]=Edição Electrónica
GenericName[pt_BR]=Editoração eletrônica
GenericName[ru]=Настольная издательская система
GenericName[sl]=Namizno založništvo
GenericName[sr]=Стоно издаваштво
GenericName[ss]=Kushicelela ku desktop
GenericName[sv]=Desktop Publishing
GenericName[th]=เดสก์ทอปพับลิชชิง
GenericName[tr]=Masaüstü Yayıncılık
GenericName[tt]=Өстәл нәшрияты
GenericName[uk]=Видавнича система
GenericName[uz]=Кичик нашриёт
GenericName[ven]=U andadza Desikithopo
GenericName[xh]=Upapasho lwe Desktop
GenericName[zh_CN]=桌面出版
GenericName[zh_TW]=桌面出版
GenericName[zu]=Ukushicilelwa kwe-Desktop
TryExec=scribus
Exec=scribus %f
Terminal=false
MimeType=application/vnd.scribus;
Categories=Qt;Graphics;Publishing;
StartupWMClass=scribus
StartupNotify=false
X-AppInstall-Package=scribus
X-AppInstall-Section=main
X-KDE-SubstituteUID=false
X-KDE-Username=
X-Desktop-File-Install-Version=0.22

[X-Property::X-KDE-NativeExtension]
Type=QString
Value=.sla
DocPath=scribus
[tomasz@arch ~]$

**Comment by varlesh** [comment]
Ok i add soon.
@cgklein i add  "masterpdfeditor3" as symlynk to "pdfeditor"

**Comment by FadeMind** [comment]
Master PDF Editor desktop file:
[tomasz@arch ~]$ cat /usr/share/applications/masterpdfeditor.desktop 
[Desktop Entry]
Type=Application
Name=Master PDF Editor
GenericName=Master PDF Editor
Comment=Edit your PDF and XPS files
Exec=/opt/masterpdfeditor/masterpdfeditor3 %f
**Icon=pdfeditor.png**
Categories=Office;Publishing;
MimeType=application/pdf
[tomasz@arch ~]$ 

Looking:
![screenshot_20160216_211659](https://cloud.githubusercontent.com/assets/9846948/13089795/a3a40b08-d4f2-11e5-9561-bcc0afcf304f.png)

**Comment by varlesh** [comment]
png and showing?

**Comment by varlesh** [comment]
pdfeditor.png not available only pdfeditor.svg

**Comment by cgklein** [comment]
Thanks to all, don't forget to update ppa.

**Comment by varlesh** [comment]
Ok, update later
