### ISSUE TITLE
[KDE Plasma 5] Splash screen idea

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-suite#98]
I prepared (based on breeze files templates) KSplash:
![screenshot_20160222_120847](https://cloud.githubusercontent.com/assets/9846948/13218943/4a35bace-d96d-11e5-8875-c94437a81b9a.png)

![screenshot_20160222_140319](https://cloud.githubusercontent.com/assets/9846948/13218946/572897d8-d96d-11e5-9cad-12289deecc46.png)

Main files are stored in:

    $ tree /usr/share/plasma/look-and-feel/com.github.varlesh.papirus/
    /usr/share/plasma/look-and-feel/com.github.varlesh.papirus/
    ├── contents
    │   ├── components
    │   │   └── artwork
    │   │       └── background.jpg
    │   ├── defaults
    │   ├── previews
    │   │   ├── preview.png
    │   │   └── splash.png
    │   └── splash
    │       ├── images
    │       └── Splash.qml
    └── metadata.desktop
    
    6 directories, 6 files

Tarball: 
[com.github.varlesh.papirus.tar.gz](https://github.com/varlesh/papirus-suite/files/140612/com.github.varlesh.papirus.tar.gz)

But You need additional free wallpaper for setup this ;) @varlesh

**Comment by varlesh** [comment]
Maybe later, because i'm not use KDE now.

**Comment by FadeMind** [comment]
:+1:  @varlesh
